### ISSUE TITLE
Question re. testing routes

### ISSUE THREAD

**Issue by dylanparry** [pshrmn/react-router-test-context#1]
Hi,

I was wondering if it's possible to use this module to test that a particular component is being rendered for a given URL? At the moment I'm doing a simple smoke test to check that a component renders:

```javascript
import React from 'react';
import { shallow } from 'enzyme';
import createRouterContext from 'react-router-test-context';

import Layout from '../layout';

const setup = () =>
{
  const context = createRouterContext();
  const wrapper = shallow(<Layout />, { context });

  return {
    wrapper,
  };
};

describe('Layout', () =>
{
  test('render', () =>
  {
    const { wrapper } = setup();

    expect(wrapper.exists()).toBe(true);
  });
});
```

Where the component I'm testing is like:

```javascript
import React from 'react';
import { Link, Switch, Route } from 'react-router-dom';

import HomeView from '../home';
import TestView from '../test';

const layout = () => (
  <div>
    <p>My App</p>

    <Switch>
      <Route path="/test" component={TestView} />
      <Route path="/" component={HomeView} />
    </Switch>
  </div>
);

export default layout;
```

I'd like to extend my tests to check that individual routes are working correctly, something like:

```javascript
test('"/test" route', () =>
{
  const { wrapper } = setup('/test'); // Would need to set the route in the setup function

  expect(wrapper.contains(TestView)).toBe(true);
});
```

Is that possible this this, or am I stuck with using a full mount?

Thanks :)

**Comment by pshrmn** [comment]
For a single `<Route>`, you can do a shallow render to determine that the expected component renders. This does not work with a `<Switch>` however because of how shallow renders work. If you want to test the results of a `<Switch>`, you will have to do a full mount.

```js
import React from 'react'
import { shallow, mount } from 'enzyme'
import createContext from 'react-router-test-context'
import { Switch, Route } from 'react-router'

describe('route', () => {
  it('renders the expected component', () => {
    const location = { pathname: '/test' }
    const context = createContext({ location })

    const Test = () => <div>This is only a test</div>

    const wrapper = shallow(<Route path='/test' component={Test}/>, { context })
    const testMatch = wrapper.find(Test)

    expect(testMatch.exists()).toBe(true)
  })
})

describe('switch', () => {
  it('renders the expected component', () => {
    const location = { pathname: '/two' }
    const context = createContext({ location })

    const One = () => <div>One</div>
    const Two = () => <div>Two</div>

    const wrapper = mount((
      <Switch>
        <Route path='/one' component={One}/>
        <Route path='/two' component={Two}/>
      </Switch>
    ), { context })

    const oneMatch = wrapper.find(One)
    const twoMatch = wrapper.find(Two)

    expect(oneMatch.exists()).toBe(false)
    expect(twoMatch.exists()).toBe(true)
  })
})
```

**Comment by dylanparry** [comment]
Thanks, that's really helpful. It's a shame I have to use a full mount, but at least I know how to do it now 👍

**Comment by pshrmn** [comment]
If only `shallow` has a sibling method `shallowish` that let you specify how many levels you want to render :man_shrugging:

**Comment by dylanparry** [comment]
Hi. I've only just got around to trying this, and while your sample code works, it throws an error if I extract the Switch that's being tested into its own component:

```javascript
describe('switch', () =>
{
  it('renders the expected component', () =>
  {
    const location = { pathname: '/two' };
    const context = createContext({ location });

    const One = () => <div>One</div>;
    const Two = () => <div>Two</div>;
    const TestSwitch = () => (
      <Switch>
        <Route path="/one" component={One} />
        <Route path="/two" component={Two} />
      </Switch>
    );

    const wrapper = mount((
      <TestSwitch />
    ), { context });

    const oneMatch = wrapper.find(One);
    const twoMatch = wrapper.find(Two);

    expect(oneMatch.exists()).toBe(false);
    expect(twoMatch.exists()).toBe(true);
  });
});
```

I get `TypeError: Cannot read property 'route' of undefined` thrown on the line where the mounting occurs. This means I'm unable to test any components containing `Switch` if they're defined in a separate file too.

Any ideas?

**Comment by pshrmn** [comment]
Alright, so the issue seems to be related to `<TestSwitch>` not defining `contextTypes`. When I add the following lines, it works.

```js
TestSwitch.contextTypes = {
  router: React.PropTypes.object
}
```

It appears to be that the root component must be context-aware or else none of its children will be able to access the context. The root component does not have to implement `getChildContext`, so it isn't as if it is "hosting" the context.

That solution doesn't really make sense to me because that isn't how the context works elsewhere in React. I'll add a note about this to the `README` and take a look at this later to see where `mount` differs from an actual mount.

**Comment by pshrmn** [comment]
From the [`<ReactWrapperComponent>` source](https://github.com/airbnb/enzyme/blob/v2.8.0/src/ReactWrapperComponent.jsx#L74-L90)

> For full rendering, we are using this wrapper component to provide context if it is specified in both the options AND the child component defines `contextTypes` statically OR the merged context types for all children (the node component or deeper children) are specified in options parameter under childContextTypes. In that case, we define both a `getChildContext()` function and a `childContextTypes` prop.

So the solution would be to either have the root component define `contextTypes`:

```js
const Test = (props) => <div>{props.children}</div>
Test.contextTypes = {
  router: React.PropTypes.object
}
const wrapper = mount(<Test />, { context })
```

or to pass a context object through the `options` object.

```js
const Test = (props) => <div>{props.children}</div>
const childContextTypes = {
  router: React.PropTypes.object
}
const wrapper = mount(<Test />, { context, childContextTypes })

```
