### ISSUE TITLE
TypeError: router.setRouteLeaveHook is not a function

### ISSUE THREAD

**Issue by xuchen81** [pshrmn/react-router-test-context#2]
Using options 2, however, i am getting 
```
TypeError: router.setRouteLeaveHook is not a function
```
my router looks
```
{ history:
   { action: 'POP',
     location: { pathname: '/', search: '', hash: '', key: 'ch3ac9' },
     _listeners: [],
     listen: [Function: listen],
     push: [Function: push],
     replace: [Function: replace],
     _notifyListeners: [Function: _notifyListeners],
     createHref: [Function: createHref] },
  route:
   { match: { path: '/', url: '/', isExact: true, params: {} },
     location: { pathname: '/', search: '', hash: '', key: 'ch3ac9' } },
  staticContext: undefined }
```
which does not have setRouteLeaveHook function.

**Comment by pshrmn** [comment]
Which version of React Router are you using? This package only works with React Router v4 (I should probably update the README to make this more clear).

**Comment by xuchen81** [comment]
I am using react-router@2.8.1, let me update my react-router, and see it that works. Thanks

**Comment by pshrmn** [comment]
React Router v4 is a major update, so it requires more of a rewrite than jump bumping versions. For earlier versions, you can check out [this testing documentation](https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Testing.md) (it uses v3 which is the same as v2 but with deprecated code removed).
