### ISSUE TITLE
    Warning: Failed context type: The context `router` is marked as required in `Component`, but its value is `undefined`.

### ISSUE THREAD

**Issue by sviat-barbutsa** [pshrmn/react-router-test-context#4]
Hello. I'm trying to use this package to mock the router context but it still doesn't work event after context providing.

Here is my test.

 Btw I also have a question. Even when I'm using the _MemoryRouter_  and _mount_ feature how I can test some method of my _real_ component. _enzymeWrapper.instance()_ doesn't work because the root component is _MemoryRouter_
Thanks for any help.

```
import * as React from "react";
// import { MemoryRouter } from "react-router-dom";
import {shallow, ShallowWrapper} from "enzyme";
import createRouterContext from 'react-router-test-context'
import Overview from "../src/modules/customer/Overview";
import { profilesStore } from "../src/store";

let overview: ShallowWrapper<undefined, undefined>;

beforeEach(function() {
		overview=shallow(

			<Overview profilesStore={profilesStore}/>,
			{ context : createRouterContext() }
	)
});

describe('Overview component test suite', () => {
    it('should have an one section with id container', () => {
        expect(overview.find("#container")).toHaveLength(1);
    });
});
```

Here is the issue message
 _Warning: Failed context type: The context `router` is marked as required in
`Component`, but its value is `undefined`.
        in Link
        in header
        in section
        in default_1_

**Comment by pshrmn** [comment]
Probably related to this https://github.com/pshrmn/react-router-test-context#mount.

**Comment by sviat-barbutsa** [comment]
I don't sure that it's really answer. Unfortunately, I can't test in now. But thanks for a quick answer, I'll close the issue.
